SHELL := /bin/bash
.PHONY: x
x:
	@$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk; \
	$(MAKE) --no-print-directory --silent --question make-bash.mk;
