dir := ab/cd/ef/g
# 1,000 character path
p100 := $(dir);$(dir);$(dir);$(dir);$(dir);$(dir);$(dir);$(dir);$(dir);$(dir);
p1000 := $(p100);$(p100);$(p100);$(p100);$(p100);$(p100);$(p100);$(p100);$(p100);$(p100);
# 100 sed using bash
SHELL := /bin/bash

.PHONY: sed-bash
sed-bash:
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
	echo '$(p1000)' | sed 's/;/ /g' > /dev/null
